#ifndef MAILBOX_H
#define MAILBOX_H
extern volatile unsigned int mailbox[36];

#define MAILBOX_REQUEST_CODE 0
#define MAILBOX_BUFFER_SIZE (35 << 2)

// Mailbox channels
#define MAILBOX_CHANNEL_POWER 0
#define MAILBOX_CHANNEL_FB 1
#define MAILBOX_CHANNEL_VUART 2
#define MAILBOX_CHANNEL_VCHIQ 3
#define MAILBOX_CHANNEL_LEDS 4
#define MAILBOX_CHANNEL_BTNS 5
#define MAILBOX_CHANNEL_TOUCH 6
#define MAILBOX_CHANNEL_COUNT 7
#define MAILBOX_CHANNEL_PROP 8

// Mailbox tags
#define MAILBOX_TAG_SET_PHSICAL_DISPLAY 0x00048003
#define MAILBOX_TAG_SET_VIRTUAL_BUFFER 0x00048004
#define MAILBOX_TAG_SET_VIRTUAL_OFFSET 0x00048009
#define MAILBOX_TAG_SET_DEPTH 0x00048005
#define MAILBOX_TAG_SET_PIXEL_ORDER 0x00048006
#define MAILBOX_TAG_ALLOCATE_BUFFER 0x00040001
#define MAILBOX_TAG_GET_PITCH 0x00040008
#define MAILBOX_TAG_LAST 0

int mailbox_call(unsigned char ch);
#endif
